version: "3.7"

services:

  fhir-server:
    container_name: fhir-server
    image: "ghcr.io/num-codex/blaze:0.1.0"
    environment:
      BASE_URL: "http://fhir-server:8080"
      JAVA_TOOL_OPTIONS: "-Xmx4g"
      LOG_LEVEL: debug
    ports:
    - ${PORT_BLAZE_FHIR:-127.0.0.1:8081}:8080
    volumes:
    - "blaze-data:/app/data"

  db:
    image: postgres:12.6-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fhir

volumes:
  blaze-data:
